# AirIntel

# Notebook 02 — Data Validation

## Objective

This notebook validates the extracted AirIntel dataset before any cleaning is performed.

The objectives are:

- Validate the dataset schema.
- Analyze missing values.
- Detect duplicate records.
- Verify data types.
- Validate timestamps.
- Check city and state consistency.
- Validate pollutant ranges.
- Generate a comprehensive validation report.

No modifications are made to the dataset in this notebook.

In [1]:
# Import required libraries

import warnings
from pathlib import Path

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:.2f}".format)

In [2]:
# Define project directories

PROJECT_ROOT = Path("..")

PROCESSED_DATA = PROJECT_ROOT / "data" / "processed"
REPORTS = PROJECT_ROOT / "reports"

In [3]:
# Load the processed dataset

df = pd.read_parquet(
    PROCESSED_DATA / "raw_airintel.parquet"
)

df.head()

,City,State,Latitude,Longitude,Datetime,Year,Month,Day,Hour,Day_of_Week,Day_Name,Week_of_Year,Is_Weekend,Quarter,Season,Time_of_Day,Temp_2m_C,Temp_80m_C,Temp_120m_C,Temp_180m_C,Humidity_Percent,Dew_Point_C,Humidity_Category,Wind_Speed_10m_kmh,Wind_Speed_80m_kmh,Wind_Speed_120m_kmh,Wind_Dir_10m,Wind_Gusts_kmh,Wind_Category,Wind_Stagnation,Precipitation_mm,Rain_mm,Is_Raining,Heavy_Rain,Pressure_MSL_hPa,Surface_Pressure_hPa,Solar_Radiation_Wm2,Direct_Radiation_Wm2,Diffuse_Radiation_Wm2,UV_Index,Cloud_Cover_Percent,Cloud_Low_Percent,Cloud_Mid_Percent,Cloud_High_Percent,Is_Daytime,Sunshine_Seconds,PM2_5_ugm3,PM10_ugm3,PM_Ratio,CO_ugm3,NO2_ugm3,SO2_ugm3,O3_ugm3,Dust_ugm3,NH3_ugm3,AOD,US_AQI,US_AQI_PM25,US_AQI_PM10,US_AQI_NO2,US_AQI_O3,US_AQI_CO,EU_AQI,EU_AQI_PM25,EU_AQI_PM10,AQI_Category,PM25_Category_India,Temp_Inversion,Inversion_Strength_C,Festival_Period,Crop_Burning_Season
0,Agartala,Tripura,23.83,91.29,2022-08-05 00:00:00,2022,8,5,0,4,Friday,31,0,3,Monsoon,Night,26.70,NaN,NaN,NaN,91,25.10,Very_Humid,5.40,NaN,NaN,172,11.20,Moderate,0,0.00,0.00,0,0,1004.40,1003.00,0.00,0.00,0.00,NaN,100,0,7,100,0,0.00,14.80,21.50,0.69,197.00,21.80,2.70,32.00,0.00,NaN,0.14,NaN,NaN,NaN,11.00,16.00,2,NaN,NaN,NaN,None,Good,0,NaN,0,0
1,Agartala,Tripura,23.83,91.29,2022-08-05 01:00:00,2022,8,5,1,4,Friday,31,0,3,Monsoon,Night,26.40,NaN,NaN,NaN,93,25.20,Very_Humid,4.50,NaN,NaN,166,9.00,Light,0,0.00,0.00,0,0,1003.90,1002.50,0.00,0.00,0.00,NaN,100,3,4,100,0,0.00,15.70,22.80,0.69,196.00,18.50,3.00,33.00,0.00,NaN,0.14,NaN,NaN,NaN,9.00,14.00,2,NaN,NaN,NaN,None,Good,0,NaN,0,0
2,Agartala,Tripura,23.83,91.29,2022-08-05 02:00:00,2022,8,5,2,4,Friday,31,0,3,Monsoon,Night,26.10,NaN,NaN,NaN,95,25.20,Very_Humid,3.80,NaN,NaN,163,7.60,Light,0,0.00,0.00,0,0,1003.50,1002.10,0.00,0.00,0.00,NaN,100,2,2,100,0,0.00,16.30,23.50,0.69,196.00,15.10,3.30,34.00,0.00,NaN,0.15,NaN,NaN,NaN,7.00,14.00,2,NaN,NaN,NaN,None,Good,0,NaN,0,0
3,Agartala,Tripura,23.83,91.29,2022-08-05 03:00:00,2022,8,5,3,4,Friday,31,0,3,Monsoon,Night,26.00,NaN,NaN,NaN,96,25.20,Very_Humid,3.70,NaN,NaN,151,6.80,Light,0,0.00,0.00,0,0,1003.00,1001.60,0.00,0.00,0.00,NaN,100,0,1,100,0,0.00,17.60,25.40,0.69,197.00,14.10,3.30,32.00,0.00,NaN,0.15,NaN,NaN,NaN,7.00,14.00,2,NaN,NaN,NaN,None,Good,0,NaN,0,0
4,Agartala,Tripura,23.83,91.29,2022-08-05 04:00:00,2022,8,5,4,4,Friday,31,0,3,Monsoon,Night,25.80,NaN,NaN,NaN,97,25.20,Very_Humid,4.10,NaN,NaN,128,6.80,Light,0,0.00,0.00,0,0,1002.90,1001.50,0.00,0.00,0.00,NaN,100,0,1,100,0,0.00,18.20,26.20,0.69,199.00,13.90,3.20,30.00,0.00,NaN,0.14,NaN,NaN,NaN,7.00,14.00,2,NaN,NaN,NaN,None,Good,0,NaN,0,0

In [4]:
# Summarize the dataset

dataset_summary = pd.DataFrame({

    "Metric": [
        "Rows",
        "Columns",
        "Cities",
        "States",
        "Date Range"
    ],

    "Value": [
        len(df),
        df.shape[1],
        df["City"].nunique(),
        df["State"].nunique(),
        f"{df['Datetime'].min()} → {df['Datetime'].max()}"
    ]

})

dataset_summary

       Metric                                      Value
0        Rows                                     842160
1     Columns                                         71
2      Cities                                         29
3      States                                         29
4  Date Range  2022-08-05 00:00:00 → 2025-11-26 23:00:00

In [5]:
# Review dataset schema

schema = pd.DataFrame({

    "Column": df.columns,

    "Data Type": df.dtypes.astype(str),

    "Missing Values": df.isna().sum(),

    "Missing %": (
        df.isna().mean()*100
    ).round(2)

})

schema

,Column,Data Type,Missing Values,Missing %
City,City,object,0,0.00
State,State,object,0,0.00
Latitude,Latitude,float64,0,0.00
Longitude,Longitude,float64,0,0.00
Datetime,Datetime,object,0,0.00
...,...,...,...,...
PM25_Category_India,PM25_Category_India,object,2,0.00
Temp_Inversion,Temp_Inversion,int64,0,0.00
Inversion_Strength_C,Inversion_Strength_C,float64,842160,100.00
Festival_Period,Festival_Period,int64,0,0.00
Crop_Burning_Season,Crop_Burning_Season,int64,0,0.00

In [6]:
# Calculate missing values

missing_summary = pd.DataFrame({

    "Missing Values": df.isna().sum(),

    "Missing %": (
        df.isna().mean()*100
    ).round(2)

}).sort_values(
    "Missing %",
    ascending=False
)

missing_summary

                     Missing Values  Missing %
Temp_180m_C                  842160     100.00
Temp_80m_C                   842160     100.00
Wind_Speed_120m_kmh          842160     100.00
Wind_Speed_80m_kmh           842160     100.00
NH3_ugm3                     842160     100.00
...                             ...        ...
Is_Raining                        0       0.00
Heavy_Rain                        0       0.00
Pressure_MSL_hPa                  0       0.00
State                             0       0.00
Crop_Burning_Season               0       0.00

[71 rows x 2 columns]

In [7]:
# Identify duplicate records

duplicate_count = df.duplicated().sum()

duplicate_summary = pd.DataFrame({

    "Metric":[
        "Duplicate Rows"
    ],

    "Value":[
        duplicate_count
    ]

})

duplicate_summary

           Metric  Value
0  Duplicate Rows      0

In [8]:
# Summarize feature datatypes

datatype_summary = pd.DataFrame(

    df.dtypes,
    columns=["Data Type"]

)

datatype_summary

                     Data Type
City                    object
State                   object
Latitude               float64
Longitude              float64
Datetime                object
...                        ...
PM25_Category_India     object
Temp_Inversion           int64
Inversion_Strength_C   float64
Festival_Period          int64
Crop_Burning_Season      int64

[71 rows x 1 columns]

In [9]:
# Validate datetime information

datetime_summary = pd.DataFrame({

    "Metric":[
        "Start Date",
        "End Date",
        "Unique Timestamps"
    ],

    "Value":[
        df["Datetime"].min(),
        df["Datetime"].max(),
        df["Datetime"].nunique()
    ]

})

datetime_summary

              Metric                Value
0         Start Date  2022-08-05 00:00:00
1           End Date  2025-11-26 23:00:00
2  Unique Timestamps                29040

In [10]:
# Summarize observations for each city

city_summary = (

    df.groupby("City")

    .size()

    .reset_index(name="Records")

    .sort_values(
        "Records",
        ascending=False
    )

)

city_summary

                  City  Records
0             Agartala    29040
15            Itanagar    29040
27  Thiruvananthapuram    29040
26              Shimla    29040
25            Shillong    29040
24              Ranchi    29040
23              Raipur    29040
22               Patna    29040
21              Panaji    29040
20              Mumbai    29040
19             Lucknow    29040
18             Kolkata    29040
17              Kohima    29040
16              Jaipur    29040
14              Imphal    29040
1            Ahmedabad    29040
13           Hyderabad    29040
12            Guwahati    29040
11            Gurugram    29040
10             Gangtok    29040
9                Delhi    29040
8             Dehradun    29040
7              Chennai    29040
6           Chandigarh    29040
5          Bhubaneswar    29040
4               Bhopal    29040
3            Bengaluru    29040
2               Aizawl    29040
28       Visakhapatnam    29040

In [11]:
# Summarize observations for each state

state_summary = (

    df.groupby("State")

    .size()

    .reset_index(name="Records")

    .sort_values(
        "Records",
        ascending=False
    )

)

state_summary

                State  Records
0      Andhra Pradesh    29040
15            Manipur    29040
27        Uttarakhand    29040
26      Uttar Pradesh    29040
25            Tripura    29040
24          Telangana    29040
23         Tamil Nadu    29040
22             Sikkim    29040
21          Rajasthan    29040
20             Punjab    29040
19             Odisha    29040
18           Nagaland    29040
17            Mizoram    29040
16          Meghalaya    29040
14        Maharashtra    29040
1   Arunachal Pradesh    29040
13     Madhya Pradesh    29040
12             Kerala    29040
11          Karnataka    29040
10          Jharkhand    29040
9    Himachal Pradesh    29040
8             Haryana    29040
7             Gujarat    29040
6                 Goa    29040
5               Delhi    29040
4        Chhattisgarh    29040
3               Bihar    29040
2               Assam    29040
28        West Bengal    29040

In [12]:
# Validate geographic coordinates

coordinate_summary = pd.DataFrame({

    "Metric":[
        "Minimum Latitude",
        "Maximum Latitude",
        "Minimum Longitude",
        "Maximum Longitude"
    ],

    "Value":[
        df["Latitude"].min(),
        df["Latitude"].max(),
        df["Longitude"].min(),
        df["Longitude"].max()
    ]

})

coordinate_summary

              Metric  Value
0   Minimum Latitude   8.52
1   Maximum Latitude  31.10
2  Minimum Longitude  72.57
3  Maximum Longitude  94.11

In [13]:
# Summarize pollutant ranges

pollutants = [

    "PM2_5_ugm3",
    "PM10_ugm3",
    "NO2_ugm3",
    "SO2_ugm3",
    "CO_ugm3",
    "O3_ugm3"

]

range_summary = pd.DataFrame({

    "Minimum":[
        df[col].min()
        for col in pollutants
    ],

    "Maximum":[
        df[col].max()
        for col in pollutants
    ]

},
index=pollutants)

range_summary

            Minimum  Maximum
PM2_5_ugm3     0.10   581.10
PM10_ugm3      0.10  3263.40
NO2_ugm3      -0.20   336.00
SO2_ugm3      -0.20   424.60
CO_ugm3       56.00 14504.00
O3_ugm3      -11.00   930.00

In [14]:
# Calculate dataset memory usage

memory_usage = (

    df.memory_usage(
        deep=True
    ).sum()

    /1024**2

)

print(
    f"Memory Usage : {memory_usage:.2f} MB"
)

Memory Usage : 856.94 MB

In [15]:
# Identify negative pollutant values

pollutants = [
    "PM2_5_ugm3",
    "PM10_ugm3",
    "NO2_ugm3",
    "SO2_ugm3",
    "CO_ugm3",
    "O3_ugm3"
]

negative_summary = pd.DataFrame({

    "Negative Values": [
        (df[col] < 0).sum()
        for col in pollutants
    ]

},
index=pollutants)

negative_summary

            Negative Values
PM2_5_ugm3                0
PM10_ugm3                 0
NO2_ugm3                  2
SO2_ugm3                  4
CO_ugm3                   0
O3_ugm3                  82

In [16]:
# Summarize pollutant statistics

range_validation = df[pollutants].describe().T

range_validation

               count   mean    std    min    25%    50%    75%      max
PM2_5_ugm3 842160.00  34.74  30.84   0.10  14.70  25.90  44.20   581.10
PM10_ugm3  842160.00  56.26  83.84   0.10  21.50  39.00  66.40  3263.40
NO2_ugm3   842160.00  16.13  20.81  -0.20   3.70   9.00  19.90   336.00
SO2_ugm3   842160.00  13.60  20.62  -0.20   2.80   6.90  15.80   424.60
CO_ugm3    842160.00 450.89 434.55  56.00 235.00 333.00 508.00 14504.00
O3_ugm3    842160.00  80.48  46.20 -11.00  47.00  73.00 108.00   930.00

In [17]:
# Validate city-state mapping

city_state_validation = (

    df.groupby("City")["State"]

    .nunique()

    .reset_index(name="Unique States")

)

city_state_validation

                  City  Unique States
0             Agartala              1
1            Ahmedabad              1
2               Aizawl              1
3            Bengaluru              1
4               Bhopal              1
5          Bhubaneswar              1
6           Chandigarh              1
7              Chennai              1
8             Dehradun              1
9                Delhi              1
10             Gangtok              1
11            Gurugram              1
12            Guwahati              1
13           Hyderabad              1
14              Imphal              1
15            Itanagar              1
16              Jaipur              1
17              Kohima              1
18             Kolkata              1
19             Lucknow              1
20              Mumbai              1
21              Panaji              1
22               Patna              1
23              Raipur              1
24              Ranchi              1
25            Shillong              1
26              Shimla              1
27  Thiruvananthapuram              1
28       Visakhapatnam              1

In [18]:
# Identify inconsistent city-state mappings

invalid_city_state = city_state_validation[
    city_state_validation["Unique States"] > 1
]

invalid_city_state

Empty DataFrame
Columns: [City, Unique States]
Index: []

In [19]:
# Validate city coordinates

coordinate_validation = (

    df.groupby("City")[["Latitude", "Longitude"]]

    .agg(["min", "max"])

)

coordinate_validation

                   Latitude       Longitude
                        min   max       min   max
City
Agartala              23.83 23.83     91.29 91.29
Ahmedabad             23.02 23.02     72.57 72.57
Aizawl                23.73 23.73     92.72 92.72
Bengaluru             12.97 12.97     77.59 77.59
Bhopal                23.26 23.26     77.41 77.41
Bhubaneswar           20.30 20.30     85.82 85.82
Chandigarh            30.73 30.73     76.78 76.78
Chennai               13.08 13.08     80.27 80.27
Dehradun              30.32 30.32     78.03 78.03
Delhi                 28.61 28.61     77.21 77.21
Gangtok               27.34 27.34     88.61 88.61
Gurugram              28.46 28.46     77.03 77.03
Guwahati              26.14 26.14     91.74 91.74
Hyderabad             17.39 17.39     78.49 78.49
Imphal                24.82 24.82     93.94 93.94
Itanagar              27.08 27.08     93.61 93.61
Jaipur                26.91 26.91     75.79 75.79
Kohima                25.68 25.68     94.11 94.11
Kolkata               22.57 22.57     88.36 88.36
Lucknow               26.85 26.85     80.95 80.95
Mumbai                19.08 19.08     72.88 72.88
Panaji                15.49 15.49     73.83 73.83
Patna                 25.59 25.59     85.14 85.14
Raipur                21.25 21.25     81.63 81.63
Ranchi                23.34 23.34     85.31 85.31
Shillong              25.58 25.58     91.89 91.89
Shimla                31.10 31.10     77.17 77.17
Thiruvananthapuram     8.52  8.52     76.94 76.94
Visakhapatnam         17.69 17.69     83.22 83.22

In [20]:
# Check duplicate timestamps for each city

duplicate_timestamp = (

    df.groupby(["City", "Datetime"])

    .size()

    .reset_index(name="Count")

)

duplicate_timestamp = duplicate_timestamp[
    duplicate_timestamp["Count"] > 1
]

duplicate_timestamp

Empty DataFrame
Columns: [City, Datetime, Count]
Index: []

In [21]:
# Identify constant columns

constant_columns = [

    col

    for col in df.columns

    if df[col].nunique() == 1

]

constant_columns

['Temp_Inversion']

In [22]:
# Identify low variance numerical features

numeric_columns = df.select_dtypes(include=np.number).columns

variance_summary = pd.DataFrame({

    "Variance": df[numeric_columns].var()

}).sort_values(
    "Variance"
)

variance_summary.head(20)

                     Variance
Temp_Inversion           0.00
Heavy_Rain               0.00
PM_Ratio                 0.03
Wind_Stagnation          0.06
Festival_Period          0.09
AOD                      0.09
Crop_Burning_Season      0.16
Is_Raining               0.16
Is_Weekend               0.20
Is_Daytime               0.25
Rain_mm                  0.84
Precipitation_mm         0.84
Year                     0.99
Quarter                  1.24
Day_of_Week              4.00
Month                   11.64
US_AQI_CO               15.15
Wind_Speed_10m_kmh      25.78
Latitude                30.73
Pressure_MSL_hPa        32.48

In [23]:
# Calculate unique values for every feature

unique_summary = pd.DataFrame({

    "Unique Values": df.nunique()

}).sort_values(
    "Unique Values"
)

unique_summary

                      Unique Values
Inversion_Strength_C              0
Wind_Speed_120m_kmh               0
Wind_Speed_80m_kmh                0
NH3_ugm3                          0
Temp_180m_C                       0
...                             ...
SO2_ugm3                       2512
CO_ugm3                        5024
Datetime                      29040
Sunshine_Seconds              62326
PM_Ratio                     126158

[71 rows x 1 columns]

In [24]:
# Calculate overall data quality score

quality_checks = {

    "Duplicate Rows":
        duplicate_count == 0,

    "Missing Values":
        df.isna().sum().sum() == 0,

    "Negative Pollutants":
        negative_summary["Negative Values"].sum() == 0,

    "City-State Mapping":
        len(invalid_city_state) == 0,

    "Constant Columns":
        len(constant_columns) == 0

}

quality_score = (

    sum(quality_checks.values())

    / len(quality_checks)

) * 100

quality_report = pd.DataFrame({

    "Validation Check": quality_checks.keys(),

    "Passed": quality_checks.values()

})

quality_report

      Validation Check  Passed
0       Duplicate Rows    True
1       Missing Values   False
2  Negative Pollutants   False
3   City-State Mapping    True
4     Constant Columns   False

In [25]:
# Display overall quality score

print(f"Overall Data Quality Score : {quality_score:.1f}%")

Overall Data Quality Score : 40.0%

## Final Validation Summary

In [26]:
# Summarize validation results

validation_summary = pd.DataFrame({

    "Metric": [

        "Rows",

        "Columns",

        "Cities",

        "States",

        "Duplicate Rows",

        "Columns with Missing Values",

        "Negative Pollutant Values",

        "Constant Columns",

        "Quality Score",

        "Memory Usage (MB)"

    ],

    "Value": [

        len(df),

        df.shape[1],

        df["City"].nunique(),

        df["State"].nunique(),

        duplicate_count,

        (df.isna().sum() > 0).sum(),

        negative_summary["Negative Values"].sum(),

        len(constant_columns),

        round(quality_score, 2),

        round(memory_usage,2)

    ]

})

validation_summary

                        Metric     Value
0                         Rows 842160.00
1                      Columns     71.00
2                       Cities     29.00
3                       States     29.00
4               Duplicate Rows      0.00
5  Columns with Missing Values     18.00
6    Negative Pollutant Values     88.00
7             Constant Columns      1.00
8                Quality Score     40.00
9            Memory Usage (MB)    856.94

In [27]:
# Save validation report

validation_summary.to_csv(

    REPORTS / "validation_report.csv",

    index=False

)

print("Validation report saved successfully.")

Validation report saved successfully.

## Notebook Summary

The dataset has been successfully validated.

### Outputs

- validation_report.csv

The next notebook will focus on cleaning the validated dataset by handling missing values, invalid records, duplicate records and outliers.